"""feat: agregar dimensiones psicometricas y datos_fisicos a Perro

Revision ID: 2a25e1e56ef6
Revises: 7ee21f732bd9
Create Date: 2025-09-15 11:24:16.190644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a25e1e56ef6'
down_revision = '7ee21f732bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energia', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('apego_vinculo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('regulacion_emocional', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exploracion_libertad', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('datos_fisicos', sa.JSON(), nullable=True))
        batch_op.drop_column('requiere_experiencia')
        batch_op.drop_column('tiempo_requerido')
        batch_op.drop_column('apego_esperado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apego_esperado', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tiempo_requerido', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('requiere_experiencia', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('datos_fisicos')
        batch_op.drop_column('exploracion_libertad')
        batch_op.drop_column('regulacion_emocional')
        batch_op.drop_column('apego_vinculo')
        batch_op.drop_column('energia')

    # ### end Alembic commands ###
