"""add MatchUsuario model and psicometric fields to Perro

Revision ID: 6ce8329a4e93
Revises: c785eb9287d7
Create Date: 2025-08-06 16:35:33.165594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce8329a4e93'
down_revision = 'c785eb9287d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tiempo_disponible', sa.Integer(), nullable=False),
    sa.Column('experiencia', sa.Integer(), nullable=False),
    sa.Column('apego_emocional', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_requerido', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requiere_experiencia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('apego_esperado', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perros', schema=None) as batch_op:
        batch_op.drop_column('apego_esperado')
        batch_op.drop_column('requiere_experiencia')
        batch_op.drop_column('tiempo_requerido')

    op.drop_table('match_usuarios')
    # ### end Alembic commands ###
