"""Add imagen uno y dos to Perro

Revision ID: 77cb9673be96
Revises: 6ce8329a4e93
Create Date: 2025-08-08 22:53:31.124627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cb9673be96'
down_revision = '6ce8329a4e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_card_uno', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagen_card_dos', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perros', schema=None) as batch_op:
        batch_op.drop_column('imagen_card_dos')
        batch_op.drop_column('imagen_card_uno')

    # ### end Alembic commands ###
