"""feat : Actualizando datos Encuesta Form

Revision ID: 7ee21f732bd9
Revises: 5a323573140c
Create Date: 2025-09-15 11:17:27.676192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee21f732bd9'
down_revision = '5a323573140c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datos_fisicos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_usuarios', schema=None) as batch_op:
        batch_op.drop_column('datos_fisicos')

    # ### end Alembic commands ###
