"""update MatchUsuario model with 4 dimensiones

Revision ID: 9d0b64432926
Revises: 2a25e1e56ef6
Create Date: 2025-09-17 09:49:30.078396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0b64432926'
down_revision = '2a25e1e56ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
